[package]
name = "hyprwalld"
version.workspace = true
edition = "2024"

[dependencies]
anyhow = "1.0.104"
calloop = "0.14.4"
calloop-wayland-source = "0.4.1"
clap = { version = "4.6.6", features = ["derive"] }
glow = "0.18.0"
hyprwall-config = { version = "0.1.0", path = "../hyprwall-config" }
hyprwall-ipc = { version = "0.1.0", path = "../hyprwall-ipc" }
khronos-egl = { version = "6.0.0", features = ["dynamic"] }
libc = "0.2"
libmpv2 = { version = "6.0.0", features = ["render"] }
smithay-client-toolkit = "0.21.1"
wayland-client = "0.31.15"
wayland-egl = "0.32.11"
wayland-protocols-wlr = { version = "0.3.12", features = ["client"] }

[dev-dependencies]
tempfile = "3.27.0"
