[package]
name = "hyprwall-gui"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
dirs = "6.0.0"
hyprwall-config = { version = "0.1.0", path = "../../hyprwall-config" }
hyprwall-ipc = { version = "0.1.0", path = "../../hyprwall-ipc" }
libc = "0.2"
libmpv2 = "6.0.0"
notify = "6"
notify-debouncer-mini = "0.4"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-shell = "2"
tempfile = "3.27.0"
